# Generated by Django 3.1.5 on 2021-01-21 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_QuestionAnswer', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Question',
        ),
    ]
