# Generated by Django 3.1.5 on 2021-01-25 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_QuestionAnswer', '0005_commentinanswer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='commentinanswer',
            options={'ordering': ('created_at',)},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ('-created_at',)},
        ),
    ]
