# Generated by Django 3.1.5 on 2021-01-21 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Article', '0005_auto_20210121_0158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(),
        ),
    ]
