# Generated by Django 3.1.5 on 2021-01-23 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Quiz', '0003_auto_20210124_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizquestion',
            name='answer',
            field=models.CharField(choices=[(models.CharField(max_length=500), 'option 1'), (models.CharField(max_length=500), 'option 2'), (models.CharField(max_length=500), 'option 3'), (models.CharField(max_length=500), 'option 4')], default=(models.CharField(max_length=500), 'option 1'), max_length=2),
        ),
    ]
