# Generated by Django 3.1.5 on 2021-01-23 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Quiz', '0004_auto_20210124_0028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizquestion',
            name='answer',
            field=models.CharField(choices=[('A', models.CharField(max_length=500)), ('B', models.CharField(max_length=500)), ('C', models.CharField(max_length=500)), ('D', models.CharField(max_length=500))], default=('A', models.CharField(max_length=500)), max_length=2),
        ),
    ]
