# Generated by Django 3.1.5 on 2021-01-23 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Quiz', '0006_auto_20210124_0031'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuizQuestion',
        ),
    ]
